# Generated by Django 5.1.2 on 2024-11-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightSensor', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], max_length=5)),
                ('temperatureSensor', models.FloatField()),
                ('motionSensor', models.CharField(choices=[('detected', 'Detected'), ('not_detected', 'Not Detected')], max_length=12)),
                ('lampState', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=3)),
                ('curtainState', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=5)),
                ('coolerState', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
