# Generated by Django 5.1.3 on 2025-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QThome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='coolerState',
            field=models.CharField(choices=[('off', 'Off'), ('low_speed', 'Low Speed'), ('medium_speed', 'Medium Speed'), ('high_speed', 'High Speed')], max_length=12),
        ),
        migrations.AlterField(
            model_name='data',
            name='curtainState',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=12),
        ),
        migrations.AlterField(
            model_name='data',
            name='lampState',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=12),
        ),
        migrations.AlterField(
            model_name='data',
            name='lightSensor',
            field=models.CharField(choices=[('very_dark', 'Very Dark'), ('dark', 'Dark'), ('medium', 'Medium'), ('bright', 'Bright'), ('very_bright', 'Very Bright')], max_length=12),
        ),
    ]
