# Generated by Django 5.1.3 on 2025-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QThome', '0002_alter_data_coolerstate_alter_data_curtainstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='coolerState',
            field=models.CharField(choices=[('off', 'Off'), ('low_speed', 'Low Speed'), ('medium_speed', 'Medium Speed'), ('high_speed', 'High Speed')], max_length=13),
        ),
        migrations.AlterField(
            model_name='data',
            name='curtainState',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=13),
        ),
        migrations.AlterField(
            model_name='data',
            name='lampState',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=13),
        ),
        migrations.AlterField(
            model_name='data',
            name='lightSensor',
            field=models.CharField(choices=[('very_dark', 'Very Dark'), ('dark', 'Dark'), ('medium', 'Medium'), ('bright', 'Bright'), ('very_bright', 'Very Bright')], max_length=13),
        ),
        migrations.AlterField(
            model_name='data',
            name='motionSensor',
            field=models.CharField(choices=[('detected', 'Detected'), ('not_detected', 'Not Detected')], max_length=13),
        ),
    ]
